    --	for index, inner in pairs(g_savedata["active"]) do
    --			if not g_savedata["playerdata"][inner]["pvp"] then
    --				server.setCharacterData(who(inner, 5), 100, true, false)
    --				server.reviveCharacter(object_id)
    --			end
